// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about_me from "./routes/about_me.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $blog_index from "./routes/blog/index.tsx";
import * as $contact from "./routes/contact.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $portfolio from "./routes/portfolio.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $FalseButton from "./islands/FalseButton.tsx";
import * as $ReturnToPreviousPage from "./islands/ReturnToPreviousPage.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about_me.tsx": $about_me,
    "./routes/api/joke.ts": $api_joke,
    "./routes/blog/index.tsx": $blog_index,
    "./routes/contact.tsx": $contact,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/portfolio.tsx": $portfolio,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/FalseButton.tsx": $FalseButton,
    "./islands/ReturnToPreviousPage.tsx": $ReturnToPreviousPage,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
